/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as HotelsHotelIdRoomsRouteImport } from './routes/hotels.$hotelId_.rooms'
import { Route as HotelsHotelIdReservationRouteImport } from './routes/hotels.$hotelId_.reservation'
import { Route as HotelsHotelIdPaymentRouteImport } from './routes/hotels.$hotelId_.payment'
import { Route as HotelsHotelIdConfirmationRouteImport } from './routes/hotels.$hotelId_.confirmation'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsHotelIdRoomsRoute = HotelsHotelIdRoomsRouteImport.update({
  id: '/hotels/$hotelId_/rooms',
  path: '/hotels/$hotelId/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdReservationRoute =
  HotelsHotelIdReservationRouteImport.update({
    id: '/hotels/$hotelId_/reservation',
    path: '/hotels/$hotelId/reservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsHotelIdPaymentRoute = HotelsHotelIdPaymentRouteImport.update({
  id: '/hotels/$hotelId_/payment',
  path: '/hotels/$hotelId/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdConfirmationRoute =
  HotelsHotelIdConfirmationRouteImport.update({
    id: '/hotels/$hotelId_/confirmation',
    path: '/hotels/$hotelId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/hotels/$hotelId/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId/rooms': typeof HotelsHotelIdRoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/hotels/$hotelId/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId/rooms': typeof HotelsHotelIdRoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/hotels/': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/hotels/$hotelId_/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId_/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId_/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId_/rooms': typeof HotelsHotelIdRoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/hotels/$hotelId'
    | '/hotels/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/hotels/$hotelId/confirmation'
    | '/hotels/$hotelId/payment'
    | '/hotels/$hotelId/reservation'
    | '/hotels/$hotelId/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/hotels/$hotelId'
    | '/hotels'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/hotels/$hotelId/confirmation'
    | '/hotels/$hotelId/payment'
    | '/hotels/$hotelId/reservation'
    | '/hotels/$hotelId/rooms'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/hotels/$hotelId'
    | '/hotels/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/hotels/$hotelId_/confirmation'
    | '/hotels/$hotelId_/payment'
    | '/hotels/$hotelId_/reservation'
    | '/hotels/$hotelId_/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  HotelsHotelIdConfirmationRoute: typeof HotelsHotelIdConfirmationRoute
  HotelsHotelIdPaymentRoute: typeof HotelsHotelIdPaymentRoute
  HotelsHotelIdReservationRoute: typeof HotelsHotelIdReservationRoute
  HotelsHotelIdRoomsRoute: typeof HotelsHotelIdRoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/rooms': {
      id: '/hotels/$hotelId_/rooms'
      path: '/hotels/$hotelId/rooms'
      fullPath: '/hotels/$hotelId/rooms'
      preLoaderRoute: typeof HotelsHotelIdRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/reservation': {
      id: '/hotels/$hotelId_/reservation'
      path: '/hotels/$hotelId/reservation'
      fullPath: '/hotels/$hotelId/reservation'
      preLoaderRoute: typeof HotelsHotelIdReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/payment': {
      id: '/hotels/$hotelId_/payment'
      path: '/hotels/$hotelId/payment'
      fullPath: '/hotels/$hotelId/payment'
      preLoaderRoute: typeof HotelsHotelIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/confirmation': {
      id: '/hotels/$hotelId_/confirmation'
      path: '/hotels/$hotelId/confirmation'
      fullPath: '/hotels/$hotelId/confirmation'
      preLoaderRoute: typeof HotelsHotelIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  HotelsHotelIdConfirmationRoute: HotelsHotelIdConfirmationRoute,
  HotelsHotelIdPaymentRoute: HotelsHotelIdPaymentRoute,
  HotelsHotelIdReservationRoute: HotelsHotelIdReservationRoute,
  HotelsHotelIdRoomsRoute: HotelsHotelIdRoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
