/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FindReservationRouteImport } from './routes/find-reservation'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as HotelIndexRouteImport } from './routes/hotel.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as PartnersRegisterRouteImport } from './routes/partners.register'
import { Route as PartnersLoginRouteImport } from './routes/partners.login'
import { Route as PartnersDashboardRouteImport } from './routes/partners.dashboard'
import { Route as HotelsHotelIdRouteImport } from './routes/hotels.$hotelId'
import { Route as HotelDashboardRouteImport } from './routes/hotel.dashboard'
import { Route as HotelSplatRouteImport } from './routes/hotel.$'
import { Route as AccountVerifyRouteImport } from './routes/account.verify'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountRewardsRouteImport } from './routes/account.rewards'
import { Route as AccountRegisterRouteImport } from './routes/account.register'
import { Route as AccountPaymentsRouteImport } from './routes/account.payments'
import { Route as AccountPaymentMethodsRouteImport } from './routes/account.payment-methods'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountLoginRouteImport } from './routes/account.login'
import { Route as AccountForgotPasswordRouteImport } from './routes/account.forgot-password'
import { Route as AccountFavouritesRouteImport } from './routes/account.favourites'
import { Route as AccountActivityRouteImport } from './routes/account.activity'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as HotelReservationsIndexRouteImport } from './routes/hotel.reservations.index'
import { Route as AccountReservationsIndexRouteImport } from './routes/account.reservations.index'
import { Route as HotelsHotelIdRoomsRouteImport } from './routes/hotels.$hotelId_.rooms'
import { Route as HotelsHotelIdReservationRouteImport } from './routes/hotels.$hotelId_.reservation'
import { Route as HotelsHotelIdPaymentRouteImport } from './routes/hotels.$hotelId_.payment'
import { Route as HotelsHotelIdConfirmationRouteImport } from './routes/hotels.$hotelId_.confirmation'
import { Route as HotelReservationsReferenceRouteImport } from './routes/hotel.reservations.$reference'
import { Route as AccountReservationsReferenceRouteImport } from './routes/account.reservations.$reference'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FindReservationRoute = FindReservationRouteImport.update({
  id: '/find-reservation',
  path: '/find-reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelIndexRoute = HotelIndexRouteImport.update({
  id: '/hotel/',
  path: '/hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRegisterRoute = PartnersRegisterRouteImport.update({
  id: '/partners/register',
  path: '/partners/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersLoginRoute = PartnersLoginRouteImport.update({
  id: '/partners/login',
  path: '/partners/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersDashboardRoute = PartnersDashboardRouteImport.update({
  id: '/partners/dashboard',
  path: '/partners/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdRoute = HotelsHotelIdRouteImport.update({
  id: '/hotels/$hotelId',
  path: '/hotels/$hotelId',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelDashboardRoute = HotelDashboardRouteImport.update({
  id: '/hotel/dashboard',
  path: '/hotel/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelSplatRoute = HotelSplatRouteImport.update({
  id: '/hotel/$',
  path: '/hotel/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyRoute = AccountVerifyRouteImport.update({
  id: '/account/verify',
  path: '/account/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/account/rewards',
  path: '/account/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/account/payments',
  path: '/account/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentMethodsRoute = AccountPaymentMethodsRouteImport.update({
  id: '/account/payment-methods',
  path: '/account/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/account/forgot-password',
  path: '/account/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountFavouritesRoute = AccountFavouritesRouteImport.update({
  id: '/account/favourites',
  path: '/account/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountActivityRoute = AccountActivityRouteImport.update({
  id: '/account/activity',
  path: '/account/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelReservationsIndexRoute = HotelReservationsIndexRouteImport.update({
  id: '/hotel/reservations/',
  path: '/hotel/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReservationsIndexRoute =
  AccountReservationsIndexRouteImport.update({
    id: '/account/reservations/',
    path: '/account/reservations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsHotelIdRoomsRoute = HotelsHotelIdRoomsRouteImport.update({
  id: '/hotels/$hotelId_/rooms',
  path: '/hotels/$hotelId/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdReservationRoute =
  HotelsHotelIdReservationRouteImport.update({
    id: '/hotels/$hotelId_/reservation',
    path: '/hotels/$hotelId/reservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsHotelIdPaymentRoute = HotelsHotelIdPaymentRouteImport.update({
  id: '/hotels/$hotelId_/payment',
  path: '/hotels/$hotelId/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsHotelIdConfirmationRoute =
  HotelsHotelIdConfirmationRouteImport.update({
    id: '/hotels/$hotelId_/confirmation',
    path: '/hotels/$hotelId/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelReservationsReferenceRoute =
  HotelReservationsReferenceRouteImport.update({
    id: '/hotel/reservations/$reference',
    path: '/hotel/reservations/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountReservationsReferenceRoute =
  AccountReservationsReferenceRouteImport.update({
    id: '/account/reservations/$reference',
    path: '/account/reservations/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-reservation': typeof FindReservationRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/hotel/$': typeof HotelSplatRoute
  '/hotel/dashboard': typeof HotelDashboardRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/partners/login': typeof PartnersLoginRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/account/': typeof AccountIndexRoute
  '/hotel/': typeof HotelIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/reservations/$reference': typeof AccountReservationsReferenceRoute
  '/hotel/reservations/$reference': typeof HotelReservationsReferenceRoute
  '/hotels/$hotelId/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId/rooms': typeof HotelsHotelIdRoomsRoute
  '/account/reservations/': typeof AccountReservationsIndexRoute
  '/hotel/reservations/': typeof HotelReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-reservation': typeof FindReservationRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/hotel/$': typeof HotelSplatRoute
  '/hotel/dashboard': typeof HotelDashboardRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/partners/login': typeof PartnersLoginRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/account': typeof AccountIndexRoute
  '/hotel': typeof HotelIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/reservations/$reference': typeof AccountReservationsReferenceRoute
  '/hotel/reservations/$reference': typeof HotelReservationsReferenceRoute
  '/hotels/$hotelId/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId/rooms': typeof HotelsHotelIdRoomsRoute
  '/account/reservations': typeof AccountReservationsIndexRoute
  '/hotel/reservations': typeof HotelReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-reservation': typeof FindReservationRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account/activity': typeof AccountActivityRoute
  '/account/favourites': typeof AccountFavouritesRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify': typeof AccountVerifyRoute
  '/hotel/$': typeof HotelSplatRoute
  '/hotel/dashboard': typeof HotelDashboardRoute
  '/hotels/$hotelId': typeof HotelsHotelIdRoute
  '/partners/dashboard': typeof PartnersDashboardRoute
  '/partners/login': typeof PartnersLoginRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/account/': typeof AccountIndexRoute
  '/hotel/': typeof HotelIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/account/reservations/$reference': typeof AccountReservationsReferenceRoute
  '/hotel/reservations/$reference': typeof HotelReservationsReferenceRoute
  '/hotels/$hotelId_/confirmation': typeof HotelsHotelIdConfirmationRoute
  '/hotels/$hotelId_/payment': typeof HotelsHotelIdPaymentRoute
  '/hotels/$hotelId_/reservation': typeof HotelsHotelIdReservationRoute
  '/hotels/$hotelId_/rooms': typeof HotelsHotelIdRoomsRoute
  '/account/reservations/': typeof AccountReservationsIndexRoute
  '/hotel/reservations/': typeof HotelReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/find-reservation'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/activity'
    | '/account/favourites'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/notifications'
    | '/account/payment-methods'
    | '/account/payments'
    | '/account/register'
    | '/account/rewards'
    | '/account/settings'
    | '/account/verify'
    | '/hotel/$'
    | '/hotel/dashboard'
    | '/hotels/$hotelId'
    | '/partners/dashboard'
    | '/partners/login'
    | '/partners/register'
    | '/account/'
    | '/hotel/'
    | '/hotels/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/reservations/$reference'
    | '/hotel/reservations/$reference'
    | '/hotels/$hotelId/confirmation'
    | '/hotels/$hotelId/payment'
    | '/hotels/$hotelId/reservation'
    | '/hotels/$hotelId/rooms'
    | '/account/reservations/'
    | '/hotel/reservations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/find-reservation'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/activity'
    | '/account/favourites'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/notifications'
    | '/account/payment-methods'
    | '/account/payments'
    | '/account/register'
    | '/account/rewards'
    | '/account/settings'
    | '/account/verify'
    | '/hotel/$'
    | '/hotel/dashboard'
    | '/hotels/$hotelId'
    | '/partners/dashboard'
    | '/partners/login'
    | '/partners/register'
    | '/account'
    | '/hotel'
    | '/hotels'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/reservations/$reference'
    | '/hotel/reservations/$reference'
    | '/hotels/$hotelId/confirmation'
    | '/hotels/$hotelId/payment'
    | '/hotels/$hotelId/reservation'
    | '/hotels/$hotelId/rooms'
    | '/account/reservations'
    | '/hotel/reservations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/find-reservation'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/account/activity'
    | '/account/favourites'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/notifications'
    | '/account/payment-methods'
    | '/account/payments'
    | '/account/register'
    | '/account/rewards'
    | '/account/settings'
    | '/account/verify'
    | '/hotel/$'
    | '/hotel/dashboard'
    | '/hotels/$hotelId'
    | '/partners/dashboard'
    | '/partners/login'
    | '/partners/register'
    | '/account/'
    | '/hotel/'
    | '/hotels/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/account/reservations/$reference'
    | '/hotel/reservations/$reference'
    | '/hotels/$hotelId_/confirmation'
    | '/hotels/$hotelId_/payment'
    | '/hotels/$hotelId_/reservation'
    | '/hotels/$hotelId_/rooms'
    | '/account/reservations/'
    | '/hotel/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FindReservationRoute: typeof FindReservationRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AccountActivityRoute: typeof AccountActivityRoute
  AccountFavouritesRoute: typeof AccountFavouritesRoute
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPaymentMethodsRoute: typeof AccountPaymentMethodsRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountVerifyRoute: typeof AccountVerifyRoute
  HotelSplatRoute: typeof HotelSplatRoute
  HotelDashboardRoute: typeof HotelDashboardRoute
  HotelsHotelIdRoute: typeof HotelsHotelIdRoute
  PartnersDashboardRoute: typeof PartnersDashboardRoute
  PartnersLoginRoute: typeof PartnersLoginRoute
  PartnersRegisterRoute: typeof PartnersRegisterRoute
  AccountIndexRoute: typeof AccountIndexRoute
  HotelIndexRoute: typeof HotelIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AccountReservationsReferenceRoute: typeof AccountReservationsReferenceRoute
  HotelReservationsReferenceRoute: typeof HotelReservationsReferenceRoute
  HotelsHotelIdConfirmationRoute: typeof HotelsHotelIdConfirmationRoute
  HotelsHotelIdPaymentRoute: typeof HotelsHotelIdPaymentRoute
  HotelsHotelIdReservationRoute: typeof HotelsHotelIdReservationRoute
  HotelsHotelIdRoomsRoute: typeof HotelsHotelIdRoomsRoute
  AccountReservationsIndexRoute: typeof AccountReservationsIndexRoute
  HotelReservationsIndexRoute: typeof HotelReservationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-reservation': {
      id: '/find-reservation'
      path: '/find-reservation'
      fullPath: '/find-reservation'
      preLoaderRoute: typeof FindReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/': {
      id: '/hotel/'
      path: '/hotel'
      fullPath: '/hotel/'
      preLoaderRoute: typeof HotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/register': {
      id: '/partners/register'
      path: '/partners/register'
      fullPath: '/partners/register'
      preLoaderRoute: typeof PartnersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/login': {
      id: '/partners/login'
      path: '/partners/login'
      fullPath: '/partners/login'
      preLoaderRoute: typeof PartnersLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/dashboard': {
      id: '/partners/dashboard'
      path: '/partners/dashboard'
      fullPath: '/partners/dashboard'
      preLoaderRoute: typeof PartnersDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId': {
      id: '/hotels/$hotelId'
      path: '/hotels/$hotelId'
      fullPath: '/hotels/$hotelId'
      preLoaderRoute: typeof HotelsHotelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/dashboard': {
      id: '/hotel/dashboard'
      path: '/hotel/dashboard'
      fullPath: '/hotel/dashboard'
      preLoaderRoute: typeof HotelDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/$': {
      id: '/hotel/$'
      path: '/hotel/$'
      fullPath: '/hotel/$'
      preLoaderRoute: typeof HotelSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify': {
      id: '/account/verify'
      path: '/account/verify'
      fullPath: '/account/verify'
      preLoaderRoute: typeof AccountVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/account/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/payments': {
      id: '/account/payments'
      path: '/account/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/payment-methods': {
      id: '/account/payment-methods'
      path: '/account/payment-methods'
      fullPath: '/account/payment-methods'
      preLoaderRoute: typeof AccountPaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/account/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/favourites': {
      id: '/account/favourites'
      path: '/account/favourites'
      fullPath: '/account/favourites'
      preLoaderRoute: typeof AccountFavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/activity': {
      id: '/account/activity'
      path: '/account/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AccountActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/reservations/': {
      id: '/hotel/reservations/'
      path: '/hotel/reservations'
      fullPath: '/hotel/reservations/'
      preLoaderRoute: typeof HotelReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reservations/': {
      id: '/account/reservations/'
      path: '/account/reservations'
      fullPath: '/account/reservations/'
      preLoaderRoute: typeof AccountReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/rooms': {
      id: '/hotels/$hotelId_/rooms'
      path: '/hotels/$hotelId/rooms'
      fullPath: '/hotels/$hotelId/rooms'
      preLoaderRoute: typeof HotelsHotelIdRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/reservation': {
      id: '/hotels/$hotelId_/reservation'
      path: '/hotels/$hotelId/reservation'
      fullPath: '/hotels/$hotelId/reservation'
      preLoaderRoute: typeof HotelsHotelIdReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/payment': {
      id: '/hotels/$hotelId_/payment'
      path: '/hotels/$hotelId/payment'
      fullPath: '/hotels/$hotelId/payment'
      preLoaderRoute: typeof HotelsHotelIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$hotelId_/confirmation': {
      id: '/hotels/$hotelId_/confirmation'
      path: '/hotels/$hotelId/confirmation'
      fullPath: '/hotels/$hotelId/confirmation'
      preLoaderRoute: typeof HotelsHotelIdConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel/reservations/$reference': {
      id: '/hotel/reservations/$reference'
      path: '/hotel/reservations/$reference'
      fullPath: '/hotel/reservations/$reference'
      preLoaderRoute: typeof HotelReservationsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/reservations/$reference': {
      id: '/account/reservations/$reference'
      path: '/account/reservations/$reference'
      fullPath: '/account/reservations/$reference'
      preLoaderRoute: typeof AccountReservationsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FindReservationRoute: FindReservationRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AccountActivityRoute: AccountActivityRoute,
  AccountFavouritesRoute: AccountFavouritesRoute,
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPaymentMethodsRoute: AccountPaymentMethodsRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountVerifyRoute: AccountVerifyRoute,
  HotelSplatRoute: HotelSplatRoute,
  HotelDashboardRoute: HotelDashboardRoute,
  HotelsHotelIdRoute: HotelsHotelIdRoute,
  PartnersDashboardRoute: PartnersDashboardRoute,
  PartnersLoginRoute: PartnersLoginRoute,
  PartnersRegisterRoute: PartnersRegisterRoute,
  AccountIndexRoute: AccountIndexRoute,
  HotelIndexRoute: HotelIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AccountReservationsReferenceRoute: AccountReservationsReferenceRoute,
  HotelReservationsReferenceRoute: HotelReservationsReferenceRoute,
  HotelsHotelIdConfirmationRoute: HotelsHotelIdConfirmationRoute,
  HotelsHotelIdPaymentRoute: HotelsHotelIdPaymentRoute,
  HotelsHotelIdReservationRoute: HotelsHotelIdReservationRoute,
  HotelsHotelIdRoomsRoute: HotelsHotelIdRoomsRoute,
  AccountReservationsIndexRoute: AccountReservationsIndexRoute,
  HotelReservationsIndexRoute: HotelReservationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
